# Generated by Django 4.0.3 on 2022-03-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0004_alter_note_lastupdated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='lastUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
